apiVersion: apps/v1
kind: Deployment
metadata:
  name: sila-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sila-api
  template:
    metadata:
      labels:
        app: sila-api
    spec:
      containers:
      - name: sila-api
        image: silaaltinguzel/akademi:2024-08-10
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 2
